[infos]
version = "1.1.0"

[paths]
arc = "rom:/arc"
umm = "sd:/ultimate/mods"
extra_paths = []

[updater]
server_ip = "104.248.50.215"
beta_updates = false

[logger]
logger_level = "Info"

[misc]
debug = false
region = "us_en"
